name: CI
on:
  pull_request:
  push:
    branches: [main]
jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Download deps
        uses: bahmutov/npm-install@v1
          with:
            install-command: npm i --force

      - name: Lint
        run: npm run lint

  typecheck:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Download deps
        uses: bahmutov/npm-install@v1
        with:
            install-command: npm i --force

      - name: Type check
        run: npm run typecheck

  test:
    name: Jest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Download deps
        uses: bahmutov/npm-install@v1
        with:
            install-command: npm i --force

      - name: Test
        run: npm run test
